"""first migration

Revision ID: 36e2bafc3b97
Revises:
Create Date: 2024-12-05 23:45:10.209265

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "36e2bafc3b97"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                     sa.Column('id', sa.String(), nullable=False),
                     sa.Column('username', sa.String(), nullable=False),
                     sa.Column('email', sa.String(), nullable=True),
                     sa.PrimaryKeyConstraint('id'),
                     if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
